# pythonのバージョン3.11を利用する
FROM python:3.11

# 作業ディレクトリをappに設定
WORKDIR /app

# appフォルダ内のファイルをAIにコピー
ADD . /app

# requirements.txtに書かれたライブラリをインストール
RUN apt update \
    apt-get install -y libgl1-mesa-dev \
    pip install --no-cache-dir -r ./docker/python/requirements.txt

# 起動時にapi.pyを実行
CMD ["python", "AI/api.py"]

