FROM openjdk:8u212-jdk-alpine

ENV TZ=Asia/Tokyo
ENV Schemaspy_URL https://github.com/schemaspy/schemaspy/releases/download/v6.1.0/schemaspy-6.1.0.jar
ENV Mysql_URL https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.30/mysql-connector-java-8.0.30.jar

WORKDIR /app

RUN apk --update add graphviz ttf-dejavu && \
    apk --update add --virtual .builddep tzdata wget libressl && \
    mkdir ./drivers && \
    wget -O ./drivers/schemaspy.jar ${Schemaspy_URL} && \
    wget -O ./drivers/mysql-connector-java-8.0.30.jar ${Mysql_URL} && \
    apk del .builddep && \
    rm -rf /var/cache/apk/*
